apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      containers:
        - name: app1nginxaks 
          image: sampleappln.azurecr.io/github-saravanan/azure-devops-github-acr-aks-app1:34
          ports:
          - containerPort: 80
